with staging as (

    select

        ticker,
        date,
        reported_currency,
        cik,
        filing_date,
        accepted_date,
        fiscal_year,
        period,
        cash_and_cash_equivalents,
        short_term_investments,
        cash_and_short_term_investments,
        net_receivables,
        accounts_receivables,
        other_receivables,
        inventory,
        prepaids,
        other_current_assets,
        total_current_assets,
        property_plant_equipment_net,
        goodwill,
        intangible_assets,
        goodwill_and_intangible_assets,
        long_term_investments,
        tax_assets,
        other_non_current_assets,
        total_non_current_assets,
        other_assets,
        total_assets,
        total_payables,
        account_payables,
        other_payables,
        accrued_expenses,
        short_term_debt,
        capital_lease_obligations_current,
        tax_payables,
        deferred_revenue,
        other_current_liabilities,
        total_current_liabilities,
        long_term_debt,
        deferred_revenue_non_current,
        deferred_tax_liabilities_non_current,
        other_non_current_liabilities,
        total_non_current_liabilities,
        other_liabilities,
        capital_lease_obligations,
        total_liabilities,
        treasury_stock,
        preferred_stock,
        common_stock,
        retained_earnings,
        additional_paid_in_capital,
        accumulated_other_comprehensive_income_loss,
        other_total_stockholders_equity,
        total_stockholders_equity,
        total_equity,
        minority_interest,
        total_liabilities_and_total_equity,
        total_investments,
        total_debt,
        net_debt,
        extracted_at

    from {{ source('balazsillovai30823', 'sp500_balance_sheets') }}

)

select * from staging
